"""add sbom observation

Revision ID: 7cb28bf85fcc
Revises: i5d6e7f8a9b0
Create Date: 2026-05-11 13:54:15.320738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb28bf85fcc'
down_revision = 'i5d6e7f8a9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('sbom_observation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('vulnerability_id', sa.String(length=50), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=True),
    sa.Column('sbom_document_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['sbom_document_id'], ['sbom_documents.id'], ),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('vuln_document_index', 'vulnerability_id', 'sbom_document_id')
    )

    # Here would be the place where we migrate old "yocto_description" columns to the new table.
    # However, it would be quite a pain since we don't know from which SBOM it originally was.

    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.drop_column('yocto_description')

    # This one has been forgotten in older migrations, migration auto generation found it
    with op.batch_alter_table('time_estimates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_estimates_variant_id'), ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yocto_description', sa.TEXT(), nullable=True))

    with op.batch_alter_table('time_estimates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_estimates_variant_id'))

    op.drop_table('sbom_observation')
    # ### end Alembic commands ###
