"""add sbom observation

Revision ID: 7cb28bf85fcc
Revises: i5d6e7f8a9b0
Create Date: 2026-05-11 13:54:15.320738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb28bf85fcc'
down_revision = 'i5d6e7f8a9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('sbom_observation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('vulnerability_id', sa.String(length=50), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=True),
    sa.Column('sbom_document_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['sbom_document_id'], ['sbom_documents.id'], ),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('vuln_document_index', 'vulnerability_id', 'sbom_document_id')
    )

    # Thanks to https://stackoverflow.com/a/61000724
    sql_random_uuid = """
lower(hex( randomblob(4)) || '-' || hex( randomblob(2))
|| '-' || '4' || substr( hex( randomblob(2)), 2) || '-'
|| substr('AB89', 1 + (abs(random()) % 4) , 1)  ||
substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6)))
"""

    op.execute(f"""
INSERT INTO sbom_observation (id, key, vulnerability_id, description, sbom_document_id)
SELECT DISTINCT
    {sql_random_uuid} AS id,
    "Yocto Description" as key,
    vulnerabilities.id AS vulnerability_id,
    vulnerabilities.yocto_description as description,
    sbom_documents.id AS sbom_document_id
FROM vulnerabilities
INNER JOIN findings ON vulnerabilities.id = findings.vulnerability_id
INNER JOIN observations ON observations.finding_id = findings.id
INNER JOIN scans ON observations.scan_id = scans.id
INNER JOIN sbom_documents ON sbom_documents.scan_id = scans.id
WHERE vulnerabilities.yocto_description IS NOT NULL
AND sbom_documents.format = 'yocto_cve_check'
""")

    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.drop_column('yocto_description')

    # This one has been forgotten in older migrations, migration auto generation found it
    with op.batch_alter_table('time_estimates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_estimates_variant_id'), ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yocto_description', sa.TEXT(), nullable=True))

    with op.batch_alter_table('time_estimates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_estimates_variant_id'))

    op.drop_table('sbom_observation')
    # ### end Alembic commands ###
